apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nats-sales-discount-sub
spec:
  selector:
    matchLabels:
      app: nats-sales-discount-sub
  replicas: 1
  template:
    metadata:
      labels:
        app: nats-sales-discount-sub
    spec:
      containers:
      - name: nats-sales-discount-sub
        image: renegmedal/ecommerce-sales-discount:1.0.1

